TeamMody/mody-server

build.gradle

security, oauth 관련 의존성 추가입니다.
#14
spring security, oauth 관련 의존성을 추가하기 위해 build.gradle 파일을 수정했습니다.
어떤 변경 사항이 있나요?

🔧 [CHORE] #14 - spring security, oauth 의존성 추가

---

.gitignore
build.gradle
src/main/generated/com/example/mody/domain/auth/entity/QRefreshToken.java
src/main/generated/com/example/mody/domain/member/entity/QMember.java
src/main/generated/com/example/mody/domain/test/entity/QTest.java
src/main/generated/com/example/mody/global/common/base/QBaseEntity.java
src/main/java/com/example/mody/domain/auth/controller/AuthController.java
src/main/java/com/example/mody/domain/auth/dto/request/MemberJoinRequest.java
src/main/java/com/example/mody/domain/auth/dto/request/MemberLoginReqeust.java
src/main/java/com/example/mody/domain/auth/handler/OAuth2SuccessHandler.java
src/main/java/com/example/mody/domain/auth/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/mody/domain/auth/jwt/JwtLoginFilter.java
src/main/java/com/example/mody/domain/auth/security/CustomUserDetails.java
src/main/java/com/example/mody/domain/auth/security/CustomUserDetailsService.java
src/main/java/com/example/mody/domain/auth/service/AuthCommandService.java
src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java
src/main/java/com/example/mody/domain/member/converter/MemberConverter.java
src/main/java/com/example/mody/domain/member/entity/Member.java
src/main/java/com/example/mody/domain/member/repository/MemberRepository.java
src/main/java/com/example/mody/domain/member/service/MemberCommandService.java
src/main/java/com/example/mody/domain/member/service/MemberCommandServiceImpl.java
src/main/java/com/example/mody/global/common/exception/code/status/MemberErrorStatus.java
src/main/java/com/example/mody/global/config/SecurityConfig.java

spring security로 회원가입 로그인 기능 구현하였습니다.
#11 
/auth/signup - 회원가입, /auth/login - 로그인으로 구현하였습니다.
login은 UsernamePasswordAuthenticationFilter를 JwtLoginFilter로 커스텀하여 구현하였습니다.
어떤 변경 사항이 있나요?
JwtAuthenticationFilter에서 토큰 검증할 때 소셜로그인, 자체로그인 토큰 추출이 findByProviderId(), findByEmail()로 달라져서 .orElseGet()으로 우선 처리해두었습니다.
그리고 소셜로그인 후 신규가입자의 경우 추가적인 정보 기입하는 api 엔드포인트는 자체 회원가입 엔드포인트와 겹치는 것 같아서 /auth/signup -> /auth/signup/oauth2로 변경해두었는데 더 좋은 생각 있으신 분 말씀해주세요!

✨ [#11] feature(Auth): 회원가입 로그인 구현

---

src/main/java/com/example/mody/domain/member/entity/Member.java
src/main/java/com/example/mody/domain/member/exception/annotation/ExistsMember.java
src/main/java/com/example/mody/domain/member/exception/validator/ExistsMemberValidator.java
src/main/java/com/example/mody/domain/post/constant/PostConstant.java
src/main/java/com/example/mody/domain/post/controller/PostController.java
src/main/java/com/example/mody/domain/post/entity/Post.java
src/main/java/com/example/mody/domain/post/entity/mapping/MemberPostLike.java
src/main/java/com/example/mody/domain/post/exception/annotation/ExistsPost.java
src/main/java/com/example/mody/domain/post/exception/validator/ExistsPostValidator.java
src/main/java/com/example/mody/domain/post/repository/MemberPostLikeRepository.java
src/main/java/com/example/mody/domain/post/service/PostCommandService.java
src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
src/main/java/com/example/mody/global/common/exception/code/status/PostErrorStatus.java

진짜 깃 꼬여서 죄송합니다. 이게 로그인 기능 찐 최종입니다.
#33 
로그인 기능 찐 최종입니다.
깃이 꼬여서 그만...
어떤 변경 사항이 있나요?

🐛 [#33] feature(Member): 로그인 기능 찐 최종

---

src/main/java/com/example/mody/domain/post/controller/PostController.java

#42 
게시글 삭제 API를 merge할 때 conflict를 해결하는 과정에서 import문을 잘못 삭제하는 바람에 action이 제대로 수행되지 않음. 따라서 해당 import문 추가
어떤 변경 사항이 있나요?

🔨 [FIX] #42-Import문 추가

---

src/main/generated/com/example/mody/domain/style/entity/QStyleImage.java
src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
src/main/java/com/example/mody/domain/style/controller/StyleController.java
src/main/java/com/example/mody/domain/style/dto/BodyTypeDTO.java
src/main/java/com/example/mody/domain/style/dto/request/StyleRecommendRequest.java
src/main/java/com/example/mody/domain/style/entity/Style.java
src/main/java/com/example/mody/domain/style/entity/StyleImage.java
src/main/java/com/example/mody/domain/style/service/StyleCommandService.java
src/main/java/com/example/mody/domain/style/service/StyleCommandServiceImpl.java
src/main/java/com/example/mody/global/common/exception/annotation/IsEmptyList.java
src/main/java/com/example/mody/global/common/exception/validator/NotEmptyListValidator.java

#39 
사용자의 체형 분석 정보를 받아와서 gpt로 보내도록 하고 스타일 추천 결과를 디비에 저장할 수 있도록 구현하였습니다.
어떤 변경 사항이 있나요?
사용자 체형 정보와 관련해서는 BodyTypeDTO에 담아서 String으로 변환 후 지피티로 넘기도록 하였습니다.
현재 memberBodyType의 body필드에 지피티 분석 결과 전체가 저장되고 있는 것 같아서 BodyTypeDTO를 body, bodyTypeName으로 구성해두었는데 이 부분은 나중에 변경이 있을 것 같은 부분이라서 확정되면 수정하도록 하겠습니다!

 ✨[FEATURE] #39 스타일 추천 결과 저장

---

src/main/java/com/example/mody/domain/bodytype/controller/BodyTypeController.java
src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeCommandService.java
src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeCommandServiceImpl.java
src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryService.java
src/main/java/com/example/mody/domain/bodytype/service/memberbodytype/MemberBodyTypeQueryServiceImpl.java
src/main/java/com/example/mody/global/config/SecurityConfig.java

체형 분석 API에 대한 코드 최적화입니다.
#47 
기존 memberId 사용을 @AuthenticationPrincipal로 수정하였고, 저희가 회의에서 진행했던 서비스 딴으로 책임을 전가하는 코드 컨벤션 형식에 맞게 코드를 리팩토링 하였습니다.
어떤 변경 사항이 있나요?
현재 GPTs를 사용할지, 단순 OpenAi API를 사용할지 확실하게 정해지지 않은 상태입니다. 그래서 만약 GPTs를 사용하게 된다면 체형 분석과 스타일 추천에 대한 코드가 수정될 수 있습니다.

🔨 [REFACTOR] #47 - 체형 분석 API 수정

---

docker-compose-dev.yml

#29 
어떤 변경 사항이 있나요?
dcoker-compose만 수정해서 올립니다!

🔧 [CHORE] #29-SSL 설정

---

src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
src/main/java/com/example/mody/domain/member/controller/MemberController.java
src/main/java/com/example/mody/domain/member/dto/response/MemberProfileResponse.java
src/main/java/com/example/mody/domain/member/entity/Member.java
src/main/java/com/example/mody/domain/member/service/MemberQueryService.java
src/main/java/com/example/mody/domain/member/service/MemberQueryServiceImpl.java
src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java

Closes #75
- 프로필 조회 API 구현
- member 엔티티에 member가 받은 총 좋아요 개수를 저장하는 필드 추가
어떤 변경 사항이 있나요?
- 살짝 급하게 만들어서 실수한 부분이 있을 수도 있습니다. 코드 리뷰 조금만 더 꼼꼼히 봐주시면 감사하겠습니다!

✨ [FEATURE] #75 - 유저 프로필 조회 API 구현

---

src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java

#72 
게시글 삭제시 해당 id의 post_report 데이터도 삭제하도록 변경하여 발생하는 외래 키 제약 조건 문제 해결
어떤 변경 사항이 있나요?

🔨 [Hotfix] #72 - 게시글 삭제 문제 해결

---

src/main/java/com/example/mody/domain/auth/controller/AuthController.java
src/main/java/com/example/mody/domain/auth/dto/request/MemberJoinRequest.java
src/main/java/com/example/mody/domain/auth/handler/OAuth2SuccessHandler.java
src/main/java/com/example/mody/domain/auth/jwt/JwtLoginFilter.java
src/main/java/com/example/mody/domain/auth/service/AuthCommandService.java
src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java
src/main/java/com/example/mody/domain/member/service/MemberCommandServiceImpl.java
src/main/java/com/example/mody/domain/style/controller/StyleController.java
src/main/java/com/example/mody/domain/style/service/StyleQueryServiceImpl.java
src/main/java/com/example/mody/global/common/exception/code/status/StyleErrorStatus.java

#66 
스타일 카테고리 조회 부분 예외 추가하였고 스웨거 예외 문서화 추가하였습니다!
어떤 변경 사항이 있나요?

📃[Docs] #66 - 예외 추가 및 정리

---

src/main/java/com/example/mody/domain/post/controller/PostController.java

#69 
수정, 삭제, 조회, 신고 API의 스웨거 예외를 추가했습니다
기존 동규님이 작성하신  API의 URL과 제 URL이 postId와 postsId로 차이가 있었는데 postId로 통일했습니다
어떤 변경 사항이 있나요?

📝 [Docs] #69 -  Post API 예외 정리 및 URL 수정

---

src/main/java/com/example/mody/domain/bodytype/controller/BodyTypeController.java
src/main/java/com/example/mody/domain/bodytype/dto/response/BodyTypeAnalysisResponse.java
src/main/java/com/example/mody/domain/image/controller/S3Controller.java
src/main/java/com/example/mody/domain/image/dto/response/PresignedUrlResponse.java
src/main/java/com/example/mody/domain/image/service/S3Service.java
src/main/java/com/example/mody/domain/post/controller/PostController.java
src/main/java/com/example/mody/domain/post/dto/request/PostCreateRequest.java
src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
src/main/java/com/example/mody/global/common/exception/code/status/BodyTypeErrorStatus.java
src/main/java/com/example/mody/global/common/exception/code/status/S3ErrorStatus.java
src/main/java/com/example/mody/global/config/RestTemplateConfig.java

#70
1. 체형 분석 관련 API 예외 처리 리팩토링 및 스웨거 문서화
2. 이미지 업로드 관련 API 예외 처리 리팩토링 및 스웨거 문서화
3. from -> of 메서드 메서드 이름 수정
4. 게시글 작성 시 presigned url의 유효 기간 1시간 넘었는지 검증하는 로직 구현
어떤 변경 사항이 있나요?
게시글 작성 시 presigned url의 유효 기간 검증 로직을 생성된 S3 url에 GET 요청을 보내서 응답값이 없으면 유효 기간이 만료 돼서 실패하도록 예외 처리를 하였는데, 더 좋은 방법이 있으면 알려주시면 감사하겠습니다!

🔨 [REFACTOR] #70 - 예외 처리 리팩토링

---

src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
src/main/java/com/example/mody/domain/member/entity/Member.java
src/main/java/com/example/mody/domain/post/controller/PostController.java
src/main/java/com/example/mody/domain/post/entity/mapping/MemberPostLike.java
src/main/java/com/example/mody/domain/post/entity/mapping/PostReport.java
src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java
src/main/java/com/example/mody/domain/style/controller/StyleController.java
src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponse.java
src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendResponses.java
src/main/java/com/example/mody/domain/style/dto/response/StyleRecommendation.java
src/main/java/com/example/mody/domain/style/entity/Style.java
src/main/java/com/example/mody/domain/style/entity/mapping/MemberStyleLike.java
src/main/java/com/example/mody/domain/style/repository/MemberStyleLikeRepository.java
src/main/java/com/example/mody/domain/style/repository/StyleCustomRepository.java
src/main/java/com/example/mody/domain/style/repository/StyleCustomRepositoryImpl.java
src/main/java/com/example/mody/domain/style/repository/StyleRepository.java
src/main/java/com/example/mody/domain/style/service/StyleCommandService.java
src/main/java/com/example/mody/domain/style/service/StyleCommandServiceImpl.java
src/main/java/com/example/mody/domain/style/service/StyleQueryService.java
src/main/java/com/example/mody/domain/style/service/StyleQueryServiceImpl.java

Closes #88 
- 스타일 추천 좋아요 기능 추가 (toggle)
- 스타일 추천 목록 조회 수정
- 스타일 id 추가  
- 요청자의 좋아요 여부 추가
- 스타일 추천 대상자의 id, 닉네임 추가  
- memberPostLike와 PostReport에 대해 cascade 설정을 걸어서 db 레벨에서 부모 post 삭제 시 삭제되도록 설정 
- 삭제와 수정 시 pathVariable과 파라미터 값이 일치하지 않아 발생하던 문제 해결 
- post 삭제 시 post 작성자의 좋아요 수가 유지되던 부분을 수정
어떤 변경 사항이 있나요?

✨ [FEATURE] #88 - 스타일 추천 좋아요 기능 추가, 목록 조회 수정

---

build.gradle
src/main/java/com/example/mody/domain/auth/controller/AuthController.java
src/main/java/com/example/mody/domain/auth/dto/request/EmailRequest.java
src/main/java/com/example/mody/domain/auth/dto/request/EmailVerificationRequest.java
src/main/java/com/example/mody/domain/auth/exception/annotation/UniqueEmail.java
src/main/java/com/example/mody/domain/auth/exception/validator/ExistsEmailValidator.java
src/main/java/com/example/mody/domain/auth/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/mody/domain/auth/repository/EmailVerificationRepository.java
src/main/java/com/example/mody/domain/auth/service/email/EmailService.java
src/main/java/com/example/mody/domain/auth/service/email/EmailServiceImpl.java
src/main/java/com/example/mody/global/common/exception/code/status/AuthErrorStatus.java
src/main/java/com/example/mody/global/config/RedisConfig.java
src/main/java/com/example/mody/global/config/SecurityConfig.java
src/main/java/com/example/mody/global/config/ThymeleafConfig.java
src/main/resources/application-local.yml
src/main/resources/templates/mail/verification-email.html

사용자가 회원 가입 하기 전에 Email 중복 확인을 하고 이메일 인증을 하는 API를 구현함
어떤 변경 사항이 있나요?

✨ [#84] feature(Email): 이메일 인증 API 기능 구현

---

src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java
src/main/java/com/example/mody/domain/member/controller/MemberController.java
src/main/java/com/example/mody/domain/member/entity/Member.java
src/main/java/com/example/mody/domain/member/repository/MemberRepository.java
src/main/java/com/example/mody/domain/member/scheduler/MemberPurgeScheduler.java
src/main/java/com/example/mody/domain/member/service/MemberCommandService.java
src/main/java/com/example/mody/domain/member/service/MemberCommandServiceImpl.java
src/main/java/com/example/mody/domain/post/entity/Post.java
src/main/java/com/example/mody/domain/post/entity/mapping/MemberPostLike.java

회원 탈퇴 기능을 구현하기 위해 Member 엔티티에 PostLike OneToMany 연관관계를 추가하고, Scheduler를 추가하여 삭제된지 한달이 지나면 매일 자정마다 삭제되도록 수정함.
#100
회원 탈퇴 기능을 구현하기 위해 Member 엔티티에 PostLike OneToMany 연관관계를 추가하고, Scheduler를 추가하여 삭제된지 한달이 지나면 매일 자정마다 삭제되도록 수정함.
어떤 변경 사항이 있나요?

✨ [#100] feature(Member): 회원탈퇴 기능

---

src/main/java/com/example/mody/domain/post/repository/PostCustomRepositoryImpl.java

Closes #97
- OrderSpecifier를 사용하여 동적으로 정렬 기준을 적용
- 기존에 bodytype이 존재하지 않던 유저의 요청 시 전부 1 혹은 0으로 정렬하도록 작성했었는데, 제대로 정렬이 이뤄지지 않는 문제가 있었음. 이를 해결 
어떤 변경 사항이 있나요?

🔨 [HOTFIX] #97 게시글 목록 조회 시 정렬 로직 수정

---

build.gradle
src/main/java/com/example/mody/domain/chatgpt/service/ChatGptService.java
src/main/java/com/example/mody/domain/recommendation/dto/response/analysis/ItemAnalysisResponse.java
src/main/java/com/example/mody/domain/recommendation/dto/response/analysis/StyleAnalysisResponse.java
src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java
src/main/java/com/example/mody/global/common/exception/code/status/CrawlerErrorStatus.java

#105 
1. 스타일 추천과 패션 아이템 추천 API에서 OpenAI API를 통해 핀터레스트 이미지를 가져오고자 함
2. 단순 프롬프트로는 핀터레스트 이미지를 가져오지 못 함
3. OpenAI function call을 사용하여 핀터레스트 api와 통신하려고 하였으나 실패 - 핀터레스트가 외부 api로 인식되어 불가능
4. 핀터레스트 페이지 크롤링을 통해 이미지 가져오기 성공
5. 크롤링 첫 구현에 28초가 걸렸지만, 성능 최적화 하여 크롤링에 6~7초 소모 -> 약 78%의 성능 개선
어떤 변경 사항이 있나요?
로컬에서는 테스트가 잘 되지만, 핀터레스트 api가 외부 api라 프론트에서 테스트할 때 CORS가 터질 수 있습니다. api 연동 시에 오류가 생기면 수정하겠습니다. 그리고 스프링 환경에서 크롤링 하는 게 처음이라 문제 있는 부분이 있을 수도 있으니, 더 나은 방법 있으시면 말해주세요!
* api 테스트
* 스타일 추천 : 섹시하고 시크한 힙/스트릿 스타일
* 핀터레스트 이미지 url : https://i.pinimg.com/236x/4b/b9/f4/4bb9f4014682c36c4368be53c2e56254.jpg
* api 테스트
* 아이템 추천 : 스트레이트 핏 가죽 자켓
* 핀터레스트 이미지 url : https://i.pinimg.com/236x/32/87/f8/3287f86756200b3c8d9d28181aaddeae.jpg

✨ [FEATURE] #105 - 핀터레스트 이미지 구현

---

src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java

#109 
컨테이너 환경에서 크롬 드라이버가 실행되지 않는 오류를 해결하였습니다.
어떤 변경 사항이 있나요?
로컬 환경에서는 핀터레스트 페이지 크롤링이 잘 되는데, 컨테이너 환경에서는 잘 안 될 수 있어서 이 부분은 계속해서 수정하겠습니다.

🔨 [HOTFIX] #109 - 크롬 드라이버 실행 오류 해결

---

src/main/java/com/example/mody/domain/auth/service/AuthCommandServiceImpl.java

리프레쉬 토큰을 디비에 저장하는 로직을 추가하였습니다.
#111 
리프레쉬 토큰 저장 로직 추가
어떤 변경 사항이 있나요?

🚨 [HOTFIX] #111- 리프레쉬 토큰 저장

---

build.gradle
src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java

#109 
컨테이너 환경에서 크롬 드라이버 실행을 못 하는 에러를 해결하기 위해 Selenium 버전을 변경하였습니다.
어떤 변경 사항이 있나요?
컨테이너 환경에서 크롬 드라이버를 못 불러오는 문제를 해결하기 위해서 구글링을 통해 해결 방법을 찾아봤습니다. 이 방법으로도 해결되지 않을 수 있어, 만약 해결 안 되면 다시 수정하겠습니다.
https://velog.io/@cobin_dev/%ED%81%AC%EB%A1%AC-%EB%93%9C%EB%9D%BC%EC%9D%B4%EB%B2%84-%EC%85%80%EB%A0%88%EB%8B%88%EC%9B%80-%EB%8F%84%EC%BB%A4-%ED%99%98%EA%B2%BD-%EC%97%B0%EB%8F%99

🔨 [HOTFIX] #109 - Selenium 버전 변경

---

src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java

#109 
컨테이너 환경에서 크롬 드라이버가 실행 안 되는 문제를 해결하기 위한 리팩토링입니다.
어떤 변경 사항이 있나요?

♻️ [Refactor] #109 - ChromeDriver 옵션 리팩토링

---

src/main/java/com/example/mody/global/config/CorsMvcConfig.java

#118 
CORS에러 수정
어떤 변경 사항이 있나요?

🚨 [HOTFIX] #118- CORS 에러 수정

---

src/main/java/com/example/mody/domain/recommendation/service/CrawlerService.java

#109 
크롬 드라이버 옵션 수정입니다.
어떤 변경 사항이 있나요?

♻️ [Refactor] #109 - ChromeDriver 옵션 수정

---

src/main/java/com/example/mody/domain/post/controller/PostController.java
src/main/java/com/example/mody/domain/post/entity/Post.java
src/main/java/com/example/mody/domain/post/service/PostCommandService.java
src/main/java/com/example/mody/domain/post/service/PostCommandServiceImpl.java

게시물 수정해서 공개범위만 수정할 수 있는 api입니다.
#121 
공개 범위만 수정할 수 있는 api입니다.
어떤 변경 사항이 있나요?

✨ [#121] feature: 게시물 공개범위 수정 api

---

src/main/java/com/example/mody/domain/post/repository/PostCustomRepositoryImpl.java

Closes #124
- 게시글 조회 api 조인 수정
어떤 변경 사항이 있나요?

[HOTFIX] #124 - 게시글 조회 api 조인 수정

---

src/main/java/com/example/mody/global/config/SecurityConfig.java

securityConfig jwt인증 필터 생성자 수정
#137 
securityConfig의 jwt인증 필터의 생성자를 수정하였습니다.
어떤 변경 사항이 있나요?

🚨 [HOTFIX] #137 jwt인증 필터 생성자 수정

---

src/main/java/com/example/mody/domain/bodytype/repository/MemberBodyTypeRepository.java
src/main/java/com/example/mody/domain/bodytype/service/BodyTypeService.java

Closes #141
- 최신 바디타입을 가져오던 메서드에 누락된 내림차순 조건 추가
어떤 변경 사항이 있나요?

🚨 [HOTFIX] #141 - 최근 바디타입을 가져오던 메서드에 누락된 내림차순 조건 추가

---

src/main/java/com/example/mody/domain/member/service/MemberCommandServiceImpl.java

…관리하지 못하고 있었기 때문에 수정 시 반영이 안됨. 따라서 메서드 내에서 member를 찾는 부분을 추가
Closes #143 
- 기존 트랜잭션 밖에서 member를 찾아서 사용하던 방식은 영속성 컨텍스트가 member를 관리하지 못하고 있었기 때문에 수정 시 반영이 안됨. 따라서 메서드 내에서 member를 찾는 부분을 추가
어떤 변경 사항이 있나요?

🚨 [HOTFIX] #143 - 로그인 완료 메서드 수정 
